%import common.WS_INLINE
%import .core (REG, immediate, LABEL, label_decl, COMMENT, _segment)
%import .instruction.instruction
%import .macro.macro_call

code_segment    : _segment{".code", _code_statement}

_code_statement : label_decl
                | instruction{REG, immediate, LABEL}
                | macro_call

# ?code_instr     : instruction{REG, immediate, LABEL}

%ignore COMMENT
%ignore WS_INLINE
