%import common (WS, WS_INLINE)
%import .code.code_segment
%import .data_text.data_segment
%import .data_text.text_segment
%import .macro.macro_def
%import core (_line, STRING, COMMENT)

program     : (WS* _top_level)* WS*

_top_level  : text_segment
            | macro_def
            | data_segment
            | code_segment
            | _line{import_file}

import_file : ".import" STRING

%ignore COMMENT
%ignore WS_INLINE
